---
title: "vignette"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 8,
  fig.height = 6
)
```

We illustrate how to use the skydivide package to combine BEAST outputs obtained using multiple subsets. 

```{r setup}
library(skydivide)
```

### Skydivide
Skydivide is the debiasing algorithm proposed in the paper by S. Liu and J. Palacios.

```{r }
K = 2  # 2 subsets are used
# create a list of log file names, output of BEAST
logpath = list(system.file("extdata", "s1.log", package = "skydivide"),
               system.file("extdata", "s2.log", package = "skydivide"))
# create a list of trees file names, output of BEAST
treepath = list(system.file("extdata", "s1.trees", package = "skydivide"),
               system.file("extdata", "s2.trees", package = "skydivide"))
# combine using skydivide
res.skydivide = combine(logpath, 
                        treepath, 
                        algo = "debias",  # run skydivide
                        num.samples = 1000,  # only the last 1000 samples in the log and tree fies are used in analysis
                        time.offset = rep(0, K),  # this is added to the times of each subsets
                        fct = 1,  # this is multiplied to the times of each subsets
                        skip = 3,  # lines to skip when reading the log files
                        tree.prior = "skyline"  # tree priors, can be skyline or skyride
                        )  
fig = plot_skydivide(res.skydivide, "title", ylim = c(0.01, 10))  # plot the reconstructed effective population sizes
fig
```


### Gaussian approximation

```{r}
# combine using Gaussian approximation
res.gaussian = combine(logpath, 
                       treepath, 
                       algo = "gaussian", 
                       skip = 3, 
                       num.samples = 1000, 
                       tree.prior = "skyline", 
                       fct = 1, # this is multiplied to the times and population sizes of each subsets
                       time.offset = rep(0, 2)
                       )
fig = plot_skydivide(res.gaussian, "title", ylim = c(0.01, 10))
fig
```

### Weiszfeld algorithm

```{r}
# combine using Weiszfeld algorithm
res.weiszfeld = combine(logpath, 
                        treepath, 
                        algo = "weiszfeld", 
                        skip = 3, 
                        tree.prior = "skyline", 
                        fct = 1, # this is multiplied to the times and population sizes of each subsets
                        time.offset = rep(0, 2)
                        )
fig = plot_skydivide(res.weiszfeld, "title", ylim = c(0.01, 10))
fig
```

